/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 model.gltf --transform
Author: SDC PERFORMANCE™️ (https://sketchfab.com/3Duae)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/free-iphone-14-pro-2023-928a8bf555224472b475b201561b2c2a
Title: (FREE) iPhone 14 Pro 2023
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import modelTrans from "./model-transformed.glb";
export function Model(props) {
  const { nodes, materials } = useGLTF(modelTrans);
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials.PaletteMaterial001}
        position={[0.013, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_5.geometry}
        material={materials.PaletteMaterial002}
        position={[0.013, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_6.geometry}
        material={materials.screen}
        position={[0.013, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_7.geometry}
        material={materials.PaletteMaterial003}
        position={[0.013, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_13.geometry}
        material={materials.PaletteMaterial004}
        position={[0.013, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/modelTrans");
